[project]
name = "calc-ai-back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pillow>=11.2.1",
    "transformers>=4.51.3",
    "uvicorn>=0.34.3",
]

